# Site settings
title: Khaliun Batmunkh
email: khaliunbatmunkh@gmail.com
description: "Khaliun Batmunkh, Graphic Designer"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://khaliun.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

exclude: [
	.gitignore,
	Gruntfile.js,
	Gemfile.lock,
	node_modules/,
	package.json,
	README.md,
	LICENSE
]

sass:
  style: :compressed

gems:
 - jekyll-sitemap